project:
  type: website

website:
  title: "evgeny.sh"
  site-url: "https://evgeny.sh"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css


