project:
  type: website

website:
  title: "evgeny.sh"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme:
      light: cosmo
    css: styles.css


